version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - easywallet

  php:
    build: ./
    expose:
      - 9000
    volumes:
      - ./:/var/www/
    networks:
      - easywallet

  db:
    build:
      context: ./docker/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: easywallet
      MYSQL_ROOT_PASSWORD: mariadb
    networks:
      - easywallet

volumes:
  mysql-data:

networks:
  easywallet:
    driver: bridge
