version: "3.9"

services:
  php:
    container_name: easy-app
    build: ./
    volumes:
      - ./:/var/www/
      - /var/www/vendor/
    depends_on:
      - nginx
      - db
    networks:
      - easywallet

  nginx:
    container_name: easy-nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - easywallet

  db:
    container_name: easy-db
    build:
      context: ./docker/mariadb/
      dockerfile: Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: easywallet
      MYSQL_ROOT_PASSWORD: mariadb
    networks:
      - easywallet

volumes:
  mysql-data:

networks:
  easywallet:
    driver: bridge